"""
AquaTrust AI — Simulator Profile Loader
Loads and parses statistical profiles, operating ranges, temporal profiles,
correlation matrices, and anomaly scenarios generated by Member 1.
"""

import os
import json
import yaml
from typing import Dict, Any, Optional


class ProfileLoader:
    """
    Loads and provides structured access to Member 1 simulator statistical artifacts.
    """

    DEFAULT_SIMULATOR_DOCS_DIR = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..", "..", "docs", "simulator")
    )

    def __init__(self, docs_dir: Optional[str] = None):
        self.docs_dir = docs_dir or self.DEFAULT_SIMULATOR_DOCS_DIR
        self._load_artifacts()

    def _load_artifacts(self):
        distributions_path = os.path.join(self.docs_dir, "parameter_distributions.json")
        operating_ranges_path = os.path.join(self.docs_dir, "operating_ranges.yaml")
        temporal_profiles_path = os.path.join(self.docs_dir, "temporal_profiles.json")
        correlation_profiles_path = os.path.join(self.docs_dir, "correlation_profiles.json")
        anomaly_scenarios_path = os.path.join(self.docs_dir, "anomaly_scenarios.yaml")

        for p, name in [
            (distributions_path, "parameter_distributions.json"),
            (operating_ranges_path, "operating_ranges.yaml"),
            (temporal_profiles_path, "temporal_profiles.json"),
            (correlation_profiles_path, "correlation_profiles.json"),
            (anomaly_scenarios_path, "anomaly_scenarios.yaml"),
        ]:
            if not os.path.exists(p):
                raise FileNotFoundError(f"Required simulator artifact missing: {name} at {p}")

        with open(distributions_path, "r", encoding="utf-8") as f:
            self.distributions: Dict[str, Any] = json.load(f)

        with open(operating_ranges_path, "r", encoding="utf-8") as f:
            self.operating_ranges: Dict[str, Any] = yaml.safe_load(f)

        with open(temporal_profiles_path, "r", encoding="utf-8") as f:
            self.temporal_profiles: Dict[str, Any] = json.load(f)

        with open(correlation_profiles_path, "r", encoding="utf-8") as f:
            self.correlation_profiles: Dict[str, Any] = json.load(f)

        with open(anomaly_scenarios_path, "r", encoding="utf-8") as f:
            self.anomaly_scenarios: Dict[str, Any] = yaml.safe_load(f)

    def get_distribution(self, facility_key: str, stage: str, param: str) -> Optional[Dict[str, Any]]:
        """
        Retrieves empirical distribution parameters for a stream.
        Example stream_key: 'FAC_UCI_URBAN_ETP_01:inlet:bod'
        """
        dists = self.distributions.get("distributions", {})
        key = f"{facility_key}:{stage}:{param}"
        if key in dists:
            return dists[key]

        # Try partial parameter lookup
        for k, v in dists.items():
            if k.endswith(f":{stage}:{param}") or k.endswith(f":{param}"):
                return v
        return None

    def get_operating_range(self, param: str) -> Optional[Dict[str, Any]]:
        """Retrieves operating ranges & boundaries for a parameter."""
        params = self.operating_ranges.get("parameters", {})
        return params.get(param.lower())

    def get_diurnal_hourly_multipliers(self) -> list:
        """Returns 24 hourly load multipliers."""
        return self.temporal_profiles.get("diurnal_flow_and_load_curves", {}).get(
            "hourly_load_multipliers", [1.0] * 24
        )

    def get_ar1_parameters(self, param: str) -> Dict[str, float]:
        """Returns AR(1) phi and sigma_epsilon parameters for a given parameter."""
        ts_params = self.temporal_profiles.get("time_series_model_parameters", {}).get("parameters", {})
        p = param.lower()
        if p in ts_params:
            return ts_params[p]
        return {"phi": 0.70, "sigma_epsilon_effluent": 1.0, "mean_reversion_rate": 0.30}

    def get_stoichiometric_ratios(self) -> Dict[str, Any]:
        """Returns stoichiometric ratios and stage removal efficiencies."""
        return self.correlation_profiles.get("stoichiometric_ratios_and_relationships", {})

    def get_anomaly_scenario_recipe(self, scenario_key: str) -> Optional[Dict[str, Any]]:
        """
        Retrieves recipe for a scenario.
        Accepts keys like 'SCENARIO_01_SENSOR_SPIKE' or 'SCENARIO_01' or '01'.
        """
        scenarios = self.anomaly_scenarios.get("scenarios", {})
        if scenario_key in scenarios:
            return scenarios[scenario_key]

        for k, v in scenarios.items():
            if scenario_key in k or k.startswith(scenario_key):
                return v
        return None
