/**
 * AquaTrust AI — Centralized Industrial SCADA Tag Registry
 * Conforms to ISA-5.1 Instrumentation Symbols and ISA-101 HMI Standards.
 * Single source of truth for all plant telemetry, alarm setpoints, and asset bindings.
 */

export const QUALITY = {
  GOOD: 'GOOD',
  UNCERTAIN: 'UNCERTAIN',
  BAD: 'BAD',
  STALE: 'STALE',
}

export const ASSET_TYPES = {
  PUMP: 'PUMP',
  BLOWER: 'BLOWER',
  VALVE: 'VALVE',
  TANK: 'TANK',
  ANALYZER: 'ANALYZER',
  DOSING: 'DOSING',
}

export const TAG_REGISTRY = {
  // --- INLET & PRIMARY SCREENING ---
  'FIT-101': {
    id: 'FIT-101',
    name: 'Raw Sewage Inflow',
    description: 'Inlet Channel Ultrasonic Flow Transmitter',
    unit: 'MLD',
    decimals: 1,
    range: [0, 80],
    normal: [35, 55],
    alarmLimits: { LL: 10, L: 20, H: 65, HH: 75 },
    responseProcedure: 'Check mechanical bar screen for blindage or blockage; inspect upstream influent sewer sump.',
    assetId: 'SCREEN-01',
    assetName: 'Mechanical Fine Bar Screen',
    assetType: ASSET_TYPES.TANK,
  },
  'LIT-101': {
    id: 'LIT-101',
    name: 'Equalization Tank Level',
    description: 'Equalization Basin Hydrostatic Level',
    unit: '%',
    decimals: 1,
    range: [0, 100],
    normal: [40, 75],
    alarmLimits: { LL: 15, L: 25, H: 85, HH: 95 },
    responseProcedure: 'Verify lift pump P-101/P-102 duty cycle; inspect level sensor transmitter diaphragm.',
    assetId: 'TK-101',
    assetName: 'Equalization Tank',
    assetType: ASSET_TYPES.TANK,
  },
  'P-101': {
    id: 'P-101',
    name: 'Raw Sewage Lift Pump 1',
    description: 'Centrifugal Submersible Lift Pump (Duty)',
    assetId: 'P-101',
    assetName: 'Raw Sewage Pump 1',
    assetType: ASSET_TYPES.PUMP,
    ratingKW: 45,
    fullLoadAmps: 78,
    writable: true,
    critical: true,
  },
  'P-102': {
    id: 'P-102',
    name: 'Raw Sewage Lift Pump 2',
    description: 'Centrifugal Submersible Lift Pump (Standby)',
    assetId: 'P-102',
    assetName: 'Raw Sewage Pump 2',
    assetType: ASSET_TYPES.PUMP,
    ratingKW: 45,
    fullLoadAmps: 78,
    writable: true,
    critical: true,
  },
  'DP-101': {
    id: 'DP-101',
    name: 'Alum Dosing Pump',
    description: 'Coagulant Metering Diaphragm Pump',
    unit: 'L/h',
    decimals: 1,
    range: [0, 50],
    normal: [10, 25],
    alarmLimits: { LL: 2, L: 5, H: 40, HH: 48 },
    responseProcedure: 'Inspect alum storage tank inventory, stroke calibration, and injection check-valve.',
    assetId: 'DP-101',
    assetName: 'Alum Dosing Skid',
    assetType: ASSET_TYPES.DOSING,
    writable: true,
    critical: true,
    maxRateOfChange: 10,
  },
  'DP-102': {
    id: 'DP-102',
    name: 'Polymer Dosing Pump',
    description: 'Flocculant Aid Metering Pump',
    unit: 'L/h',
    decimals: 1,
    range: [0, 20],
    normal: [3, 10],
    alarmLimits: { LL: 1, L: 2, H: 15, HH: 18 },
    responseProcedure: 'Inspect polymer batch maturation tank, viscosity, and progressive cavity feed line.',
    assetId: 'DP-102',
    assetName: 'Polymer Skid',
    assetType: ASSET_TYPES.DOSING,
    writable: true,
    critical: true,
    maxRateOfChange: 5,
  },

  // --- BIOLOGICAL AERATION BASIN ---
  'AIT-201': {
    id: 'AIT-201',
    name: 'Aeration Basin DO',
    description: 'Optical Dissolved Oxygen Probe',
    unit: 'mg/L',
    decimals: 2,
    range: [0, 8.0],
    normal: [2.0, 3.5],
    alarmLimits: { LL: 1.2, L: 1.8, H: 4.5, HH: 5.5 },
    responseProcedure: 'Inspect optical DO sensor cap for bio-fouling; check blower BLW-201 VFD speed and aeration headers.',
    assetId: 'BIO-201',
    assetName: 'Aeration Basin 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
    loop: true,
    writable: true,
    critical: true,
    spTag: 'AIT-201.SP',
    outTag: 'BLW-201.SPEED',
    pidParams: { kp: 2.5, ki: 0.1, kd: 0.05, mode: 'Auto', minOut: 20, maxOut: 100 },
    maxRateOfChange: 1.5,
  },
  'AIT-202': {
    id: 'AIT-202',
    name: 'Aeration Basin pH',
    description: 'Differential pH Sensor',
    unit: 'pH',
    decimals: 2,
    range: [4.0, 10.0],
    normal: [7.0, 7.8],
    alarmLimits: { LL: 6.2, L: 6.8, H: 8.2, HH: 8.8 },
    responseProcedure: 'Clean glass electrode with dilute HCl; verify acid/caustic neutralization dosing skids DP-201/DP-202.',
    assetId: 'BIO-201',
    assetName: 'Aeration Basin 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
  },
  'TIT-201': {
    id: 'TIT-201',
    name: 'Basin Temperature',
    description: 'Pt100 RTD Temperature Transmitter',
    unit: '°C',
    decimals: 1,
    range: [10, 45],
    normal: [24, 30],
    alarmLimits: { LL: 15, L: 18, H: 35, HH: 40 },
    responseProcedure: 'Verify biological basin heat dissipation; check ambient temperature transmitter Pt100 connection.',
    assetId: 'BIO-201',
    assetName: 'Aeration Basin 01',
    assetType: ASSET_TYPES.TANK,
  },
  'BLW-201': {
    id: 'BLW-201',
    name: 'Aeration Air Blower 1',
    description: 'Variable Speed Rotary Lobe Blower (Duty)',
    assetId: 'BLW-201',
    assetName: 'Air Blower 1',
    assetType: ASSET_TYPES.BLOWER,
    ratingKW: 90,
    fullLoadAmps: 155,
    writable: true,
    critical: true,
  },
  'BLW-202': {
    id: 'BLW-202',
    name: 'Aeration Air Blower 2',
    description: 'Variable Speed Rotary Lobe Blower (Standby)',
    assetId: 'BLW-202',
    assetName: 'Air Blower 2',
    assetType: ASSET_TYPES.BLOWER,
    ratingKW: 90,
    fullLoadAmps: 155,
    writable: true,
    critical: true,
  },
  'DP-201': {
    id: 'DP-201',
    name: 'Acid Neutralization Pump',
    description: 'H2SO4 Metering Pump',
    unit: 'L/h',
    decimals: 1,
    range: [0, 15],
    normal: [0, 4],
    alarmLimits: { LL: 0, L: 0, H: 10, HH: 14 },
    responseProcedure: 'Inspect sulfuric acid suction line, metering diaphragm, and emergency shower.',
    assetId: 'DP-201',
    assetName: 'Acid Neutralization Skid',
    assetType: ASSET_TYPES.DOSING,
    writable: true,
    critical: true,
    maxRateOfChange: 4,
  },
  'DP-202': {
    id: 'DP-202',
    name: 'Alkali Neutralization Pump',
    description: 'NaOH Metering Pump',
    unit: 'L/h',
    decimals: 1,
    range: [0, 15],
    normal: [0, 3],
    alarmLimits: { LL: 0, L: 0, H: 10, HH: 14 },
    responseProcedure: 'Inspect caustic soda dosing pump, check lines for crystallization, and verify pump stroke.',
    assetId: 'DP-202',
    assetName: 'Caustic Neutralization Skid',
    assetType: ASSET_TYPES.DOSING,
    writable: true,
    critical: true,
    maxRateOfChange: 4,
  },

  // --- SECONDARY CLARIFIER & SLUDGE RECYCLE (RAS/WAS) ---
  'LIT-301': {
    id: 'LIT-301',
    name: 'Sludge Blanket Level',
    description: 'Clarifier Acoustic Sludge Blanket Profiler',
    unit: 'm',
    decimals: 2,
    range: [0, 4.5],
    normal: [1.0, 1.8],
    alarmLimits: { LL: 0.3, L: 0.6, H: 2.5, HH: 3.2 },
    responseProcedure: 'Check clarifier bridge rotation, scraper torque, and increase RAS pump P-103 flow if blanket > 2.5m.',
    assetId: 'CLR-301',
    assetName: 'Secondary Clarifier',
    assetType: ASSET_TYPES.TANK,
  },
  'P-103': {
    id: 'P-103',
    name: 'Return Activated Sludge Pump (RAS)',
    description: 'Recycle Sludge Screw Centrifugal Pump',
    assetId: 'P-103',
    assetName: 'RAS Pump 1',
    assetType: ASSET_TYPES.PUMP,
    ratingKW: 22,
    fullLoadAmps: 42,
    writable: true,
    critical: true,
  },
  'P-104': {
    id: 'P-104',
    name: 'Waste Activated Sludge Pump (WAS)',
    description: 'Excess Sludge Extraction Pump',
    assetId: 'P-104',
    assetName: 'WAS Pump 1',
    assetType: ASSET_TYPES.PUMP,
    ratingKW: 15,
    fullLoadAmps: 28,
    writable: true,
    critical: true,
  },

  // --- DISINFECTION & CHLORINE CONTACT ---
  'AIT-401': {
    id: 'AIT-401',
    name: 'Free Residual Chlorine',
    description: 'Amperometric Residual Chlorine Analyzer',
    unit: 'mg/L',
    decimals: 2,
    range: [0, 5.0],
    normal: [0.8, 1.6],
    alarmLimits: { LL: 0.3, L: 0.5, H: 2.5, HH: 3.5 },
    responseProcedure: 'Check amperometric chlorine probe flow cell; adjust sodium hypochlorite dosing pump DP-401 stroke.',
    assetId: 'CCT-401',
    assetName: 'Chlorine Contact Chamber',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
  },
  'DP-401': {
    id: 'DP-401',
    name: 'NaOCl Hypochlorite Dosing Pump',
    description: 'Sodium Hypochlorite Disinfection Metering',
    unit: 'L/h',
    decimals: 1,
    range: [0, 30],
    normal: [8, 18],
    alarmLimits: { LL: 2, L: 4, H: 25, HH: 28 },
    responseProcedure: 'Inspect sodium hypochlorite day tank level, pump tubing, and degassing relief valve.',
    assetId: 'DP-401',
    assetName: 'Chlorination Skid',
    assetType: ASSET_TYPES.DOSING,
    writable: true,
    critical: true,
    maxRateOfChange: 6,
  },

  // --- FINAL TREATED EFFLUENT & CPCB OUTFALL ---
  'FIT-501': {
    id: 'FIT-501',
    name: 'Final Effluent Discharge Flow',
    description: 'Outfall Electromagnetic Flowmeter',
    unit: 'MLD',
    decimals: 1,
    range: [0, 80],
    normal: [34, 54],
    alarmLimits: { LL: 8, L: 18, H: 64, HH: 74 },
    responseProcedure: 'Check electromagnetic flowmeter lining, verify outfall weir hydraulics and discharge channel.',
    assetId: 'OUTFALL-01',
    assetName: 'Final Discharge Outfall 01',
    assetType: ASSET_TYPES.TANK,
  },
  'AIT-501': {
    id: 'AIT-501',
    name: 'Effluent pH (CPCB OCEMS)',
    description: 'Outfall Self-Cleaning pH Electrode',
    unit: 'pH',
    decimals: 2,
    range: [4.0, 10.0],
    normal: [7.1, 7.6],
    alarmLimits: { LL: 6.5, L: 6.7, H: 8.8, HH: 9.0 },
    responseProcedure: 'Inspect final outfall pH; if out of 6.5-9.0 band, divert flow via XV-501 to equalization.',
    assetId: 'OUTFALL-01',
    assetName: 'Final Discharge Outfall 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
    critical: true,
  },
  'AIT-502': {
    id: 'AIT-502',
    name: 'Effluent BOD₅ (CPCB Standard)',
    description: 'Continuous UV-Vis Surrogate BOD Analyzer',
    unit: 'mg/L',
    decimals: 1,
    range: [0, 50],
    normal: [5.0, 9.0],
    alarmLimits: { LL: 0, L: 0, H: 9.5, HH: 10.0 }, // CPCB limit <= 10.0
    responseProcedure: 'Inspect UV-Vis spectral surrogate; verify biological aeration retention time and clarifier settling.',
    assetId: 'OUTFALL-01',
    assetName: 'Final Discharge Outfall 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
    critical: true,
  },
  'AIT-503': {
    id: 'AIT-503',
    name: 'Effluent COD (CPCB Standard)',
    description: 'Online UV Spectrophotometric COD Sensor',
    unit: 'mg/L',
    decimals: 1,
    range: [0, 150],
    normal: [25, 42],
    alarmLimits: { LL: 0, L: 0, H: 45, HH: 50 }, // CPCB limit <= 50.0
    responseProcedure: 'High COD detected: verify upstream industrial batch dumping; notify pollution control board if >50 mg/L.',
    assetId: 'OUTFALL-01',
    assetName: 'Final Discharge Outfall 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
    critical: true,
  },
  'AIT-504': {
    id: 'AIT-504',
    name: 'Effluent TSS (CPCB Standard)',
    description: 'Infrared Backscatter Suspended Solids',
    unit: 'mg/L',
    decimals: 1,
    range: [0, 60],
    normal: [8.0, 14.0],
    alarmLimits: { LL: 0, L: 0, H: 18.0, HH: 20.0 }, // CPCB limit <= 20.0
    responseProcedure: 'Excess suspended solids: check clarifier sludge blanket and coagulant/polymer dosing rates.',
    assetId: 'OUTFALL-01',
    assetName: 'Final Discharge Outfall 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
    critical: true,
  },
  'AIT-505': {
    id: 'AIT-505',
    name: 'Effluent Turbidity',
    description: 'EPA 180.1 Ratio Turbidimeter',
    unit: 'NTU',
    decimals: 1,
    range: [0, 25],
    normal: [1.5, 4.0],
    alarmLimits: { LL: 0, L: 0, H: 8.0, HH: 10.0 },
    responseProcedure: 'Inspect ratio turbidimeter optical cell; verify coagulant dosing and clarifier overflow weir.',
    assetId: 'OUTFALL-01',
    assetName: 'Final Discharge Outfall 01',
    assetType: ASSET_TYPES.ANALYZER,
    calibratable: true,
    critical: true,
  },

  // --- AUTOMATED ACTUATED CONTROL VALVES ---
  'XV-101': {
    id: 'XV-101',
    name: 'Equalization Bypass Valve',
    description: 'Electric Motor Actuated Knife Gate Valve',
    assetId: 'XV-101',
    assetName: 'Bypass Gate Valve',
    assetType: ASSET_TYPES.VALVE,
  },
  'XV-201': {
    id: 'XV-201',
    name: 'Aeration Air Header Control Valve',
    description: 'Pneumatic Diaphragm Butterfly Valve',
    assetId: 'XV-201',
    assetName: 'Air Header Valve',
    assetType: ASSET_TYPES.VALVE,
  },
  'XV-301': {
    id: 'XV-301',
    name: 'Clarifier Underflow Valve',
    description: 'Pinch Valve for Sludge Draw-off',
    assetId: 'XV-301',
    assetName: 'Sludge Draw Valve',
    assetType: ASSET_TYPES.VALVE,
  },
  'XV-401': {
    id: 'XV-401',
    name: 'Chlorine Dosing Solenoid Valve',
    description: 'PTFE Isolated Solenoid Injection Valve',
    assetId: 'XV-401',
    assetName: 'NaOCl Injection Valve',
    assetType: ASSET_TYPES.VALVE,
  },
  'XV-501': {
    id: 'XV-501',
    name: 'Outfall Recirculation Diverter',
    description: 'Motorized Three-Way Diverter Valve',
    assetId: 'XV-501',
    assetName: 'Emergency Diverter Valve',
    assetType: ASSET_TYPES.VALVE,
  },
}

export function getTag(tagId) {
  return TAG_REGISTRY[tagId] || null
}

export function getAllTags() {
  return Object.values(TAG_REGISTRY)
}

export function getTagsForAsset(assetId) {
  return Object.values(TAG_REGISTRY).filter((t) => t.assetId === assetId)
}
