import { useCallback, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, FileCheck2, FileQuestion, TriangleAlert } from 'lucide-react'
import Card from '../../components/ui/Card.jsx'
import EmptyState from '../../components/ui/EmptyState.jsx'
import PageHeader from '../../components/ui/PageHeader.jsx'
import Spinner from '../../components/ui/Spinner.jsx'
import StatusBadge from '../../components/ui/StatusBadge.jsx'
import Button from '../../components/ui/Button.jsx'
import useAsyncData from '../../hooks/useAsyncData.js'
import { getReportById } from '../../services/compliance.js'
import { formatDate } from '../../utils/format.js'
import CpcbCertificateModal from '../../features/compliance/CpcbCertificateModal.jsx'

const STATUS_TONES = {
  final: 'success',
  submitted: 'info',
  draft: 'neutral',
}

const FINDING_SEVERITY_TONES = {
  high: 'danger',
  medium: 'warning',
  low: 'info',
}

const FINDING_STATUS_TONES = {
  open: 'danger',
  investigating: 'warning',
  resolved: 'success',
}

function BackLink() {
  return (
    <Link
      to="/compliance"
      className="inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-sm font-medium text-slate-600 transition-colors hover:bg-slate-100 hover:text-slate-800"
    >
      <ArrowLeft className="h-4 w-4" aria-hidden="true" />
      Back to reports
    </Link>
  )
}

export default function ComplianceReportDetailPage() {
  const { reportId } = useParams()
  const [isCertOpen, setIsCertOpen] = useState(false)

  const fetcher = useCallback(() => getReportById(reportId), [reportId])
  const { status, data, error, reload } = useAsyncData(fetcher)

  if (status === 'loading') {
    return (
      <div className="space-y-4">
        <BackLink />
        <Card bodyClassName="py-16">
          <Spinner size="lg" label="Loading report…" />
        </Card>
      </div>
    )
  }

  if (status === 'error') {
    const isNotFound = /not found/i.test(error?.message ?? '')

    return (
      <div className="space-y-4">
        <BackLink />
        {isNotFound ? (
          <EmptyState
            icon={FileQuestion}
            title="Report not found"
            description={`No report exists for ID "${reportId}". It may have been removed or the ID may be incorrect.`}
          />
        ) : (
          <EmptyState
            icon={TriangleAlert}
            title="Could not load the report"
            description="Something went wrong while loading this report."
            action={
              <div className="flex items-center gap-2">
                <Button onClick={reload}>Try again</Button>
                <Link
                  to="/compliance"
                  className="inline-flex items-center rounded-lg bg-white px-4 py-2 text-sm font-medium text-slate-700 ring-1 ring-inset ring-slate-300 transition-colors hover:bg-slate-50"
                >
                  Back to reports
                </Link>
              </div>
            }
          />
        )}
      </div>
    )
  }

  return (
    <div className="space-y-4">
      <PageHeader
        title={data.title}
        subtitle={`${data.periodStart} \u2192 ${data.periodEnd}`}
        actions={
          <div className="flex items-center gap-3">
            <StatusBadge tone={STATUS_TONES[data.status] ?? 'neutral'} label={data.status} />
            <Button
              variant="primary"
              size="sm"
              onClick={() => setIsCertOpen(true)}
              className="inline-flex items-center gap-1.5 bg-emerald-600 hover:bg-emerald-700 text-white"
            >
              <FileCheck2 className="h-4 w-4" />
              Export CPCB Return
            </Button>
          </div>
        }
      />

      <div className="grid items-start gap-4 lg:grid-cols-3">
        <Card title="Report summary" subtitle="Official STP effluent monitoring and discharge record verified under CPCB standards" className="lg:col-span-2">
          <p className="text-sm leading-relaxed text-slate-700">{data.summaryText}</p>
          <p className="mt-4 text-xs text-slate-500">Generated by {data.generatedBy}</p>
        </Card>

        <Card title="Details">
          <dl className="space-y-3 text-sm">
            <div className="flex items-center justify-between gap-3">
              <dt className="text-slate-500">Report ID</dt>
              <dd className="font-mono text-xs text-slate-700">{data.id}</dd>
            </div>
            <div className="flex items-center justify-between gap-3">
              <dt className="text-slate-500">Status</dt>
              <dd>
                <StatusBadge tone={STATUS_TONES[data.status] ?? 'neutral'} label={data.status} dot={false} />
              </dd>
            </div>
            <div className="flex items-center justify-between gap-3">
              <dt className="text-slate-500">Created</dt>
              <dd className="text-slate-700">{formatDate(data.createdAt)}</dd>
            </div>
          </dl>
        </Card>
      </div>

      {data.sections.map((section) => (
        <Card key={section.id} title={section.title}>
          <p className="text-sm leading-relaxed text-slate-700">{section.body}</p>
        </Card>
      ))}

      <Card title={`Findings (${data.findings.length})`}>
        {data.findings.length === 0 ? (
          <p className="py-2 text-center text-sm text-slate-500">No findings recorded for this report.</p>
        ) : (
          <ul className="divide-y divide-slate-100">
            {data.findings.map((finding) => (
              <li key={finding.id} className="flex flex-wrap items-center gap-2 py-3 first:pt-0 last:pb-0">
                <StatusBadge
                  tone={FINDING_SEVERITY_TONES[finding.severity] ?? 'neutral'}
                  label={`${finding.severity} severity`}
                />
                <StatusBadge
                  tone={FINDING_STATUS_TONES[finding.status] ?? 'neutral'}
                  label={finding.status}
                  dot={false}
                />
                <span className="min-w-0 flex-1 text-sm text-slate-700">{finding.description}</span>
              </li>
            ))}
          </ul>
        )}
      </Card>

      <CpcbCertificateModal
        isOpen={isCertOpen}
        onClose={() => setIsCertOpen(false)}
        report={data}
        recordId={reportId}
      />

      <div className="pt-1">
        <BackLink />
      </div>
    </div>
  )
}
